// Mock case data for development and testing
export const mockCases = [
  {
    id: 'mock-case-1',
    case_number: 'MC-2025-001',
    patient_name: 'Ravi Sharma',
    patientName: 'Ravi Sharma',
    hospital_name: 'Apollo Hospitals',
    hospitalName: 'Apollo Hospitals',
    hospital_city: 'Mumbai',
    hospitalCity: 'Mumbai',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Maharashtra',
    hospitalState: 'Maharashtra',
    patient_age: 45,
    patientAge: 45,
    patient_gender: 'male',
    patientGender: 'male',
    negligence_type: 'medication_error',
    negligenceType: 'medication_error',
    severity: 'death',
    incident_date: '2023-12-15T10:30:00.000Z',
    incidentDate: '2023-12-15T10:30:00.000Z',
    incident_description: 'Wrong medication dosage leading to fatal kidney failure',
    incidentDescription: 'Wrong medication dosage leading to fatal kidney failure',
    claim_amount: 5000000,
    claimAmount: 5000000,
    next_of_kin: 'Meera Sharma',
    nextOfKin: 'Meera Sharma',
    next_of_kin_relation: 'Spouse',
    nextOfKinRelation: 'Spouse',
    treating_doctor_name: 'Dr. Anil Mehta',
    treatingDoctorName: 'Dr. Anil Mehta',
    treating_doctor_registration: 'MH-12345',
    treatingDoctorRegistration: 'MH-12345',
    status: 'filed',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'ncrc',
    filedForum: 'ncrc',
    complaint_number: 'C-123/2023',
    complaintNumber: 'C-123/2023',
    created_at: '2024-01-10T09:00:00.000Z',
    createdAt: '2024-01-10T09:00:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-1',
    createdBy: 'user-1',
    limitation_deadline: '2026-12-15T10:30:00.000Z',
    ai_strength_score: 92,
    aiStrengthScore: 92,
    ai_analysis_completed: true,
    aiAnalysisCompleted: true,
  },
  {
    id: 'mock-case-2',
    case_number: 'MC-2025-002',
    patient_name: 'Priya Patel',
    patientName: 'Priya Patel',
    hospital_name: 'Fortis Healthcare',
    hospitalName: 'Fortis Healthcare',
    hospital_city: 'Delhi',
    hospitalCity: 'Delhi',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Delhi',
    hospitalState: 'Delhi',
    patient_age: 32,
    patientAge: 32,
    patient_gender: 'female',
    patientGender: 'female',
    negligence_type: 'surgical_error',
    negligenceType: 'surgical_error',
    severity: 'permanent_disability',
    incident_date: '2024-01-20T14:15:00.000Z',
    incidentDate: '2024-01-20T14:15:00.000Z',
    incident_description: 'Surgical instrument left inside patient during appendectomy',
    incidentDescription: 'Surgical instrument left inside patient during appendectomy',
    claim_amount: 2500000,
    claimAmount: 2500000,
    next_of_kin: 'Raj Patel',
    nextOfKin: 'Raj Patel',
    next_of_kin_relation: 'Husband',
    nextOfKinRelation: 'Husband',
    treating_doctor_name: 'Dr. Sunita Sharma',
    treatingDoctorName: 'Dr. Sunita Sharma',
    treating_doctor_registration: 'DL-54321',
    treatingDoctorRegistration: 'DL-54321',
    status: 'analysis',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'state_commission',
    filedForum: 'state_commission',
    complaint_number: 'C-124/2024',
    complaintNumber: 'C-124/2024',
    created_at: '2024-02-05T11:30:00.000Z',
    createdAt: '2024-02-05T11:30:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-2',
    createdBy: 'user-2',
    limitation_deadline: '2025-01-20T14:15:00.000Z',
    ai_strength_score: 87,
    aiStrengthScore: 87,
    ai_analysis_completed: true,
    aiAnalysisCompleted: true,
  },
  {
    id: 'mock-case-3',
    case_number: 'MC-2025-003',
    patient_name: 'Kiran Kumar',
    patientName: 'Kiran Kumar',
    hospital_name: 'AIIMS',
    hospitalName: 'AIIMS',
    hospital_city: 'New Delhi',
    hospitalCity: 'New Delhi',
    hospital_type: 'government',
    hospitalType: 'government',
    hospital_state: 'Delhi',
    hospitalState: 'Delhi',
    patient_age: 65,
    patientAge: 65,
    patient_gender: 'male',
    patientGender: 'male',
    negligence_type: 'diagnostic_error',
    negligenceType: 'diagnostic_error',
    severity: 'prolonged_suffering',
    incident_date: '2023-08-10T08:00:00.000Z',
    incidentDate: '2023-08-10T08:00:00.000Z',
    incident_description: 'Missed diagnosis of pneumonia leading to respiratory failure',
    incidentDescription: 'Missed diagnosis of pneumonia leading to respiratory failure',
    claim_amount: 1200000,
    claimAmount: 1200000,
    next_of_kin: 'Latha Kumar',
    nextOfKin: 'Latha Kumar',
    next_of_kin_relation: 'Wife',
    nextOfKinRelation: 'Wife',
    treating_doctor_name: 'Dr. Amit Singh',
    treatingDoctorName: 'Dr. Amit Singh',
    treating_doctor_registration: 'AIIMS-789',
    treatingDoctorRegistration: 'AIIMS-789',
    status: 'investigation',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'district_commission',
    filedForum: 'district_commission',
    complaint_number: 'C-125/2023',
    complaintNumber: 'C-125/2023',
    created_at: '2024-01-15T16:45:00.000Z',
    createdAt: '2024-01-15T16:45:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-1',
    createdBy: 'user-1',
    limitation_deadline: '2025-08-10T08:00:00.000Z',
    ai_strength_score: 78,
    aiStrengthScore: 78,
    ai_analysis_completed: false,
    aiAnalysisCompleted: false,
  },
  {
    id: 'mock-case-4',
    case_number: 'MC-2025-004',
    patient_name: 'Deepika Singh',
    patientName: 'Deepika Singh',
    hospital_name: 'Max Super Speciality Hospital',
    hospitalName: 'Max Super Speciality Hospital',
    hospital_city: 'Gurgaon',
    hospitalCity: 'Gurgaon',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Haryana',
    hospitalState: 'Haryana',
    patient_age: 28,
    patientAge: 28,
    patient_gender: 'female',
    patientGender: 'female',
    negligence_type: 'birth_injury',
    negligenceType: 'birth_injury',
    severity: 'permanent_disability',
    incident_date: '2024-02-14T12:00:00.000Z',
    incidentDate: '2024-02-14T12:00:00.000Z',
    incident_description: 'Medical negligence during childbirth resulting in cerebral palsy',
    incidentDescription: 'Medical negligence during childbirth resulting in cerebral palsy',
    claim_amount: 8000000,
    claimAmount: 8000000,
    next_of_kin: 'Rohit Singh',
    nextOfKin: 'Rohit Singh',
    next_of_kin_relation: 'Husband',
    nextOfKinRelation: 'Husband',
    treating_doctor_name: 'Dr. Pooja Jain',
    treatingDoctorName: 'Dr. Pooja Jain',
    treating_doctor_registration: 'HR-98765',
    treatingDoctorRegistration: 'HR-98765',
    status: 'intake',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'state_commission',
    filedForum: 'state_commission',
    complaint_number: 'C-126/2024',
    complaintNumber: 'C-126/2024',
    created_at: '2024-03-01T10:15:00.000Z',
    createdAt: '2024-03-01T10:15:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-2',
    createdBy: 'user-2',
    limitation_deadline: '2025-02-14T12:00:00.000Z',
    ai_strength_score: null,
    aiStrengthScore: null,
    ai_analysis_completed: false,
    aiAnalysisCompleted: false,
  },
  {
    id: 'mock-case-5',
    case_number: 'MC-2025-005',
    patient_name: 'Mahesh Verma',
    patientName: 'Mahesh Verma',
    hospital_name: 'Jaslok Hospital',
    hospitalName: 'Jaslok Hospital',
    hospital_city: 'Mumbai',
    hospitalCity: 'Mumbai',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Maharashtra',
    hospitalState: 'Maharashtra',
    patient_age: 55,
    patientAge: 55,
    patient_gender: 'male',
    patientGender: 'male',
    negligence_type: 'surgical_error',
    negligenceType: 'surgical_error',
    severity: 'death',
    incident_date: '2023-09-05T09:30:00.000Z',
    incidentDate: '2023-09-05T09:30:00.000Z',
    incident_description: 'Wrong site surgery leading to fatal complications',
    incidentDescription: 'Wrong site surgery leading to fatal complications',
    claim_amount: 4500000,
    claimAmount: 4500000,
    next_of_kin: 'Sunita Verma',
    nextOfKin: 'Sunita Verma',
    next_of_kin_relation: 'Wife',
    nextOfKinRelation: 'Wife',
    treating_doctor_name: 'Dr. Rajesh Kapoor',
    treatingDoctorName: 'Dr. Rajesh Kapoor',
    treating_doctor_registration: 'MH-45678',
    treatingDoctorRegistration: 'MH-45678',
    status: 'filed',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'ncrc',
    filedForum: 'ncrc',
    complaint_number: 'C-127/2023',
    complaintNumber: 'C-127/2023',
    created_at: '2024-01-20T14:00:00.000Z',
    createdAt: '2024-01-20T14:00:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-3',
    createdBy: 'user-3',
    limitation_deadline: '2024-09-05T09:30:00.000Z',
    ai_strength_score: 94,
    aiStrengthScore: 94,
    ai_analysis_completed: true,
    aiAnalysisCompleted: true,
  },
  {
    id: 'mock-case-6',
    case_number: 'MC-2025-006',
    patient_name: 'Anita Reddy',
    patientName: 'Anita Reddy',
    hospital_name: 'Narayana Health',
    hospitalName: 'Narayana Health',
    hospital_city: 'Bengaluru',
    hospitalCity: 'Bengaluru',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Karnataka',
    hospitalState: 'Karnataka',
    patient_age: 48,
    patientAge: 48,
    patient_gender: 'female',
    patientGender: 'female',
    negligence_type: 'medication_error',
    negligenceType: 'medication_error',
    severity: 'prolonged_suffering',
    incident_date: '2024-01-12T15:20:00.000Z',
    incidentDate: '2024-01-12T15:20:00.000Z',
    incident_description: 'Insulin dosage error causing severe hypoglycemia',
    incidentDescription: 'Insulin dosage error causing severe hypoglycemia',
    claim_amount: 1800000,
    claimAmount: 1800000,
    next_of_kin: 'Raj Reddy',
    nextOfKin: 'Raj Reddy',
    next_of_kin_relation: 'Son',
    nextOfKinRelation: 'Son',
    treating_doctor_name: 'Dr. Kavita Sharma',
    treatingDoctorName: 'Dr. Kavita Sharma',
    treating_doctor_registration: 'KA-11223',
    treatingDoctorRegistration: 'KA-11223',
    status: 'analysis',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'state_commission',
    filedForum: 'state_commission',
    complaint_number: 'C-128/2024',
    complaintNumber: 'C-128/2024',
    created_at: '2024-02-10T13:45:00.000Z',
    createdAt: '2024-02-10T13:45:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-1',
    createdBy: 'user-1',
    limitation_deadline: '2025-01-12T15:20:00.000Z',
    ai_strength_score: 85,
    aiStrengthScore: 85,
    ai_analysis_completed: false,
    aiAnalysisCompleted: false,
  },
  {
    id: 'mock-case-7',
    case_number: 'MC-2025-007',
    patient_name: 'Vikram Rao',
    patientName: 'Vikram Rao',
    hospital_name: 'Manipal Hospital',
    hospitalName: 'Manipal Hospital',
    hospital_city: 'Hyderabad',
    hospitalCity: 'Hyderabad',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Telangana',
    hospitalState: 'Telangana',
    patient_age: 42,
    patientAge: 42,
    patient_gender: 'male',
    patientGender: 'male',
    negligence_type: 'diagnostic_error',
    negligenceType: 'diagnostic_error',
    severity: 'prolonged_suffering',
    incident_date: '2023-11-18T11:10:00.000Z',
    incidentDate: '2023-11-18T11:10:00.000Z',
    incident_description: 'Failure to diagnose heart attack leading to cardiac arrest',
    incidentDescription: 'Failure to diagnose heart attack leading to cardiac arrest',
    claim_amount: 3000000,
    claimAmount: 3000000,
    next_of_kin: 'Latha Rao',
    nextOfKin: 'Latha Rao',
    next_of_kin_relation: 'Daughter',
    nextOfKinRelation: 'Daughter',
    treating_doctor_name: 'Dr. Suresh Kumar',
    treatingDoctorName: 'Dr. Suresh Kumar',
    treating_doctor_registration: 'TS-55443',
    treatingDoctorRegistration: 'TS-55443',
    status: 'intake',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'district_commission',
    filedForum: 'district_commission',
    complaint_number: 'C-129/2023',
    complaintNumber: 'C-129/2023',
    created_at: '2024-01-08T12:00:00.000Z',
    createdAt: '2024-01-08T12:00:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-2',
    createdBy: 'user-2',
    limitation_deadline: '2024-11-18T11:10:00.000Z',
    ai_strength_score: null,
    aiStrengthScore: null,
    ai_analysis_completed: false,
    aiAnalysisCompleted: false,
  },
  {
    id: 'mock-case-8',
    case_number: 'MC-2025-008',
    patient_name: 'Sneha Jain',
    patientName: 'Sneha Jain',
    hospital_name: 'BLK Hospital',
    hospitalName: 'BLK Hospital',
    hospital_city: 'Delhi',
    hospitalCity: 'Delhi',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Delhi',
    hospitalState: 'Delhi',
    patient_age: 38,
    patientAge: 38,
    patient_gender: 'female',
    patientGender: 'female',
    negligence_type: 'birth_injury',
    negligenceType: 'birth_injury',
    severity: 'permanent_disability',
    incident_date: '2024-03-08T07:45:00.000Z',
    incidentDate: '2024-03-08T07:45:00.000Z',
    incident_description: 'Improper use of forceps during delivery causing brachial plexus injury',
    incidentDescription: 'Improper use of forceps during delivery causing brachial plexus injury',
    claim_amount: 6000000,
    claimAmount: 6000000,
    next_of_kin: 'Amit Jain',
    nextOfKin: 'Amit Jain',
    next_of_kin_relation: 'Husband',
    nextOfKinRelation: 'Husband',
    treating_doctor_name: 'Dr. Meera Singh',
    treatingDoctorName: 'Dr. Meera Singh',
    treating_doctor_registration: 'DL-77889',
    treatingDoctorRegistration: 'DL-77889',
    status: 'filed',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'ncrc',
    filedForum: 'ncrc',
    complaint_number: 'C-130/2024',
    complaintNumber: 'C-130/2024',
    created_at: '2024-03-15T09:30:00.000Z',
    createdAt: '2024-03-15T09:30:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-3',
    createdBy: 'user-3',
    limitation_deadline: '2025-03-08T07:45:00.000Z',
    ai_strength_score: 91,
    aiStrengthScore: 91,
    ai_analysis_completed: true,
    aiAnalysisCompleted: true,
  },
  {
    id: 'mock-case-9',
    case_number: 'MC-2025-009',
    patient_name: 'Mohandas Gandhi',
    patientName: 'Mohandas Gandhi',
    hospital_name: 'Custom Hospital',
    hospitalName: 'Custom Hospital',
    hospital_city: 'New Delhi',
    hospitalCity: 'New Delhi',
    hospital_type: 'private',
    hospitalType: 'private',
    hospital_state: 'Delhi',
    hospitalState: 'Delhi',
    patient_age: 78,
    patientAge: 78,
    patient_gender: 'male',
    patientGender: 'male',
    negligence_type: 'medication_error',
    negligenceType: 'medication_error',
    severity: 'death',
    incident_date: '2023-05-12T16:20:00.000Z',
    incidentDate: '2023-05-12T16:20:00.000Z',
    incident_description: 'Multiple medication errors leading to renal failure',
    incidentDescription: 'Multiple medication errors leading to renal failure',
    claim_amount: 2000000,
    claimAmount: 2000000,
    next_of_kin: 'Mahadevi Gandhi',
    nextOfKin: 'Mahadevi Gandhi',
    next_of_kin_relation: 'Wife',
    nextOfKinRelation: 'Wife',
    treating_doctor_name: 'Dr. Rajesh Sharma',
    treatingDoctorName: 'Dr. Rajesh Sharma',
    treating_doctor_registration: 'DL-99887',
    treatingDoctorRegistration: 'DL-99887',
    status: 'filed',
    assigned_to: null,
    assignedTo: null,
    filed_forum: 'ncrc',
    filedForum: 'ncrc',
    complaint_number: 'C-131/2023',
    complaintNumber: 'C-131/2023',
    created_at: '2023-06-01T14:20:00.000Z',
    createdAt: '2023-06-01T14:20:00.000Z',
    firm_id: 'firm-1',
    firmId: 'firm-1',
    created_by: 'user-1',
    createdBy: 'user-1',
    limitation_deadline: '2024-05-12T16:20:00.000Z',
    ai_strength_score: 96,
    aiStrengthScore: 96,
    ai_analysis_completed: true,
    aiAnalysisCompleted: true,
  },
];

export const mockDocuments = [
  {
    id: 'mock-doc-1',
    case_id: 'mock-case-1',
    caseId: 'mock-case-1',
    document_category: 'medical_report',
    documentCategory: 'medical_report',
    file_name: 'apollo_medical_report_2023.pdf',
    fileName: 'apollo_medical_report_2023.pdf',
    file_size: 2048576,
    fileSize: 2048576,
    file_path: 'https://storage.supabase.co/medical-reports/apollo_medical_report_2023.pdf',
    filePath: 'https://storage.supabase.co/medical-reports/apollo_medical_report_2023.pdf',
    upload_date: '2023-12-20T10:00:00.000Z',
    uploadDate: '2023-12-20T10:00:00.000Z',
    uploaded_by: 'user-1',
    uploadedBy: 'user-1',
    processing_status: 'completed',
    processingStatus: 'completed',
    chunk_count: 5,
    chunkCount: 5,
    case_number: 'MC-2025-001',
    caseNumber: 'MC-2025-001',
  },
  {
    id: 'mock-doc-2',
    case_id: 'mock-case-2',
    caseId: 'mock-case-2',
    document_category: 'imaging',
    documentCategory: 'imaging',
    file_name: 'fortis_ct_scan_2024.nii',
    fileName: 'fortis_ct_scan_2024.nii',
    file_size: 5242880,
    fileSize: 5242880,
    file_path: 'https://storage.supabase.co/medical-reports/fortis_ct_scan_2024.nii',
    filePath: 'https://storage.supabase.co/medical-reports/fortis_ct_scan_2024.nii',
    upload_date: '2024-02-05T14:30:00.000Z',
    uploadDate: '2024-02-05T14:30:00.000Z',
    uploaded_by: 'user-2',
    uploadedBy: 'user-2',
    processing_status: 'completed',
    processingStatus: 'completed',
    chunk_count: 12,
    chunkCount: 12,
    case_number: 'MC-2025-002',
    caseNumber: 'MC-2025-002',
  },
  {
    id: 'mock-doc-3',
    case_id: 'mock-case-3',
    caseId: 'mock-case-3',
    document_category: 'discharge_summary',
    documentCategory: 'discharge_summary',
    file_name: 'aiims_discharge_summary_2023.pdf',
    fileName: 'aiims_discharge_summary_2023.pdf',
    file_size: 1572864,
    fileSize: 1572864,
    file_path: 'https://storage.supabase.co/medical-reports/aiims_discharge_summary_2023.pdf',
    filePath: 'https://storage.supabase.co/medical-reports/aiims_discharge_summary_2023.pdf',
    upload_date: '2024-01-20T11:15:00.000Z',
    uploadDate: '2024-01-20T11:15:00.000Z',
    uploaded_by: 'user-1',
    uploadedBy: 'user-1',
    processing_status: 'completed',
    processingStatus: 'completed',
    chunk_count: 8,
    chunkCount: 8,
    case_number: 'MC-2025-003',
    caseNumber: 'MC-2025-003',
  },
];

export const mockAnalysis = [
  {
    id: 'mock-analysis-1',
    case_id: 'mock-case-1',
    caseId: 'mock-case-1',
    analysis_type: 'compensation',
    strength_score: 92,
    weakness_score: 35,
    recommendation: 'Strong case with clear negligence. File within limitation period.',
    key_findings: ['Medication error', '15 month delay in seeking care', 'Permanent injury documented'],
    risk_level: 'high',
    created_at: '2024-01-15T09:00:00.000Z',
    createdAt: '2024-01-15T09:00:00.000Z',
    created_by: 'ai',
    createdBy: 'ai',
  },
  {
    id: 'mock-analysis-2',
    case_id: 'mock-case-2',
    caseId: 'mock-case-2',
    analysis_type: 'strength',
    strength_score: 87,
    weakness_score: 42,
    recommendation: 'Proceed with surgical error claim. Consider settlement negotiation.',
    key_findings: ['Clear surgical error documentation', 'Witness statements available', 'Evidence of additional procedures'],
    risk_level: 'medium',
    created_at: '2024-02-10T14:30:00.000Z',
    createdAt: '2024-02-10T14:30:00.000Z',
    created_by: 'ai',
    createdBy: 'ai',
  },
  {
    id: 'mock-analysis-3',
    case_id: 'mock-case-3',
    caseId: 'mock-case-3',
    analysis_type: 'compensation',
    strength_score: 78,
    weakness_score: 65,
    recommendation: 'Document strength is moderate. Focus on establishing negligence linkage.',
    key_findings: ['Multiple treatment providers', 'Gap in continuity of care', 'Earlier medical records needed'],
    risk_level: 'medium-high',
    created_at: '2024-01-18T16:45:00.000Z',
    createdAt: '2024-01-18T16:45:00.000Z',
    created_by: 'ai',
    createdBy: 'ai',
  },
];

export const mockProfiles = [
  {
    id: 'user-1',
    auth_id: 'auth-1',
    full_name: 'Ravi Kapoor',
    email: 'ravi@kapoor.com',
    avatar_url: null,
    firm_id: 'firm-1',
    role: 'senior_associate',
    created_at: '2023-01-15T10:00:00.000Z',
    last_login: '2024-09-17T14:30:00.000Z',
  },
  {
    id: 'user-2',
    auth_id: 'auth-2',
    full_name: 'Priya Singh',
    email: 'priya@kapoor.com',
    avatar_url: null,
    firm_id: 'firm-1',
    role: 'associate',
    created_at: '2023-02-20T11:00:00.000Z',
    last_login: '2024-09-16T12:15:00.000Z',
  },
  {
    id: 'user-3',
    auth_id: 'auth-3',
    full_name: 'Amit Sharma',
    email: 'amit@kapoor.com',
    avatar_url: null,
    firm_id: 'firm-1',
    role: 'partner',
    created_at: '2023-03-10T09:30:00.000Z',
    last_login: '2024-09-17T16:45:00.000Z',
  },
];

export const mockFirm = {
  id: 'firm-1',
  name: 'Kapoor & Associates',
  email: 'contact@kapoor.com',
  address: '123 Legal Street, Law District, Mumbai',
  contact_person: 'Ravi Kapoor',
  contact_phone: '+91-9876543210',
  logo_url: 'https://storage.supabase.co/firms/kapoor-logo.png',
  subscription_tier: 'premium',
  created_at: '2023-01-01T00:00:00.000Z',
  last_billed: '2024-08-01T00:00:00.000Z',
  active: true,
};